### ISSUE TITLE
[Idea] Option for HTML Only Downloads

### ISSUE THREAD

**Issue by yeymour** [lmmx/tabsave#1]
An option to download webpages as HTML Only would be great. 

Note: I'm not sure if you are still looking to update this extension any more but it has been a life saver for me. Thank you for making this.

**Comment by lmmx** [comment]
Ah thank you, glad to hear :smile: I'm unclear what else a web page would save as though, web pages should save as .htm (I just tried it on this page for example) - could you give me an example of what you mean?

**Comment by yeymour** [comment]
When using the normal Save As prompt from webpages you have the option to save as "Webpage, Complete" and "Webpage, HTML Only". There may be little difference between the two but for my purposes it appears that when using HTML Only the file opens faster in Excel (which I use to process the webpages I have saved). I assume this is because it doesn't save images when saving webpages with "Webpage, HTML Only".

**Comment by lmmx** [comment]
Ah I see, no, the downloaded file will just be "HTML only", there's no way it can store images in a `.htm` format. I think it should be doing what you expect it to do.
